name: Build Electron App

on:
  push:
    tags: ["v*"]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run build

      - name: Build packages
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            npm run build-win
          elif [ "$RUNNER_OS" == "Linux" ]; then
            npm run build-linux
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: dist/
